services:
  web:
    build:
      context: .
    ports:
      - "8649:8649"
    volumes:
      - /ontap/user/agrouaze/sources/git/reference_iw_safe_ifr_collections/merge_jolina_lagoon.parquet:/data/catalogue.parquet
      - /ontap/user/agrouaze/sources/git/reference_iw_safe_ifr_collections/s1iw_catalogue/localconfig_second_real.yml:/data/config.yml